### ISSUE TITLE
vimrc_mini does not call .vimrc.local

### ISSUE THREAD

**Issue by ser** [kepbod/ivim#26]
vimrc_mini does not call .vimrc.local - is there any reason for that behaviour?

**Comment by kepbod** [comment]
Yes, you are right. vimrc_mini is designed for fast and basic usage, so many plugins and functions were removed. If you want to call .vimrc.local, you could use ivim.

**Comment by hyperreal-info** [comment]
Ok, so I would suggest to include to source for example .vimrc_mini.local - as it is important to have a possibility to modify default settings

**Comment by ser** [comment]
Ok, so I would suggest to include to source for example .vimrc_mini.local - as it is important to have a possibility to modify default settings

**Comment by kepbod** [comment]
Thanks for your suggestion. I have already added sources to call .vimrc.local in vimrc_mini.
