### ISSUE TITLE
在一个文档中，当我的光标在某个单词上，我如何快速的进行这个单词的搜索呢？

### ISSUE THREAD

**Issue by hanzhong-yan** [kepbod/ivim#28]
问题：比如，我的光标在文档的单词‘morning’上，我如何快速的利用ivim的插件进行morning的搜索，
需求
     1:在本文档中检索，
     2：在vim的buffer list中检索 ， 
     3：在vim本pwd的目录树下面进行检索

我现在的做法：
     1:在normal模式下，手动输入：‘/v<morning>’
     2:需要检索grep的写法，至于ivim的那个强大的检索abolish还不熟练,现在用的比较多的是：空格+f，空格+b
     3：不会

请会的老师，不吝赐教，谢谢！
我还是vim的新手！

**Comment by kepbod** [comment]
ivim使用了[Unite](https://github.com/Shougo/unite.vim)插件的一些功能去实现你描述的功能2和3，对于这些功能我用的不是太多，你可以参考他们的文档。除此之外，[CtrlP](https://github.com/ctrlpvim/ctrlp.vim)插件也可以实现类似功能，只不过我当时选用了unite，如果你喜欢CtrlP，也可以研究一些。也欢迎提出你的看法，我希望可以把ivim完善的更加通用遍历，谢谢！

**Comment by hanzhong-yan** [comment]
好的，我学习下Unite 和 CtrlP . Thank you!
