### ISSUE TITLE
request color name

### ISSUE THREAD

**Issue by latel** [kepbod/ivim#43]
![image](https://cloud.githubusercontent.com/assets/5621862/21747718/e46e52fa-d5ab-11e6-9858-218b0d07ae1b.png)

what's the name of this coloscheme? cannot find anywhere in your configurations.

tried: 
Plugin 'morhetz/gruvbox'
Plugin 'jacoborus/tender.vim'
Plugin 'kristijanhusak/vim-hybrid-material'

none of these looks the same.

**Comment by kepbod** [comment]
The name of this color is [nord-vim](https://github.com/arcticicestudio/nord-vim).
