### ISSUE TITLE
Error detected while processing /root/.vim/plugged/ale/after/plugin/ale.vim:

### ISSUE THREAD

**Issue by ser** [kepbod/ivim#44]
Hi, a fresh installation today with ```/tmp/setup.sh -m``` gives
```
$ vim .bashrc
Error detected while processing /root/.vim/plugged/ale/after/plugin/ale.vim:
line    7:
E121: Undefined variable: g:ale_emit_conflict_warnings
E15: Invalid expression: !g:ale_emit_conflict_warnings
Press ENTER or type command to continue
```

**Comment by kepbod** [comment]
Could you try to remove all the ivim folder first and reinstall it again?

**Comment by ser** [comment]
why? i wrote clearly that it's a fresh installation :)

**Comment by kepbod** [comment]
I could not reproduce your error, so I suspected that there are some old files prevent the installation process. Maybe I am wrong, but currently I could not find this bug.

**Comment by kepbod** [comment]
Sorry for the inconvenience made for you. For most bugs I could not figure out, I generally delete all the old stuffs and reinstall it freshly, and most bugs could be solved.
