### ISSUE TITLE
Theme not rendering correctly on mac os when using brew installed vim

### ISSUE THREAD

**Issue by nujabse** [kepbod/ivim#47]
when using this vim config with vim installed by homebrew, the them looks wired:
![image](https://user-images.githubusercontent.com/9455367/41189703-b61b8012-6c04-11e8-9e82-2df60ff11c2c.png)

while using vi, the theme is showing correctly, can't figure out why?
![image](https://user-images.githubusercontent.com/9455367/41189720-fb7070d2-6c04-11e8-8d2c-e70357a87f18.png)

outputs of `which vim && which vi`:
```bash
which vim && which vi
/usr/local/bin/vim
/usr/bin/vi
```

**Comment by kepbod** [comment]
What is the version of your vim?
